// content for archives pages
export const en = {
  "title": "The Mari Angryneer Archives",
  "toc": "Table of Contents",
  "robotTitle": "Robot",
  "robotTabPg": "Robot tab page",
  "robotTabBack": "Back of robot tab page",
  "robotImg1": "img src",
  "robotText1": "Text for img 1",
  "robotImg2": "img src",
  "robotText2": "Text for img 2",
  "robotImg3": "img src",
  "robotText3": "Text for img 3",
  "robotImg4": "img src",
  "robotText4": "Text for img 4",
  "robotImg5": "img src",
  "robotText5": "Text for img 5",
  "robotImg6": "img src",
  "robotText6": "Text for img 6",
  "robotImg7": "img src",
  "robotText7": "Text for img 7",
  "robotImg8": "img src",
  "robotText8": "Text for img 8",
  "robotImg9": "img src",
  "robotText9": "Text for img 9",
  "robotPage4": "Robot page 4 en",
  "robotPage5": "Robot page 5 en",
  "robotPage6": "Robot page 6 en",
  "kioskTabPg": "Kiosk tab page",
  "kioskTabBack": "Back of kiosk tab page",
  "kioskPage1": "Kiosk page 1 en",
  "kioskPage2": "Kiosk page 2 en",
  "kioskPage3": "Kiosk page 3 en",
  "kioskPage4": "Kiosk page 4 en",
  "kioskPage5": "Kiosk page 5 en",
  "kioskPage6": "Kiosk page 6 en",
  "websiteTabPg": "Website tab page",
  "websiteTabBack": "Back of website tab page",
  "websitePage1": "Website page 1 en",
  "websitePage2": "Website page 2 en",
  "websitePage3": "Website page 3 en",
  "websitePage4": "Website page 4 en",
  "websitePage5": "Website page 5 en",
  "websitePage6": "Website page 6 en",
  "videoTabPg": "Video tab page",
  "videoTabBack": "Back of video tab page",
  "videoPage1": "Video page 1 en",
  "videoPage2": "Video page 2 en",
  "videoPage3": "Video page 3 en",
  "videoPage4": "Video page 4 en",
  "videoPage5": "Video page 5 en",
  "videoPage6": "Video page 6 en",
  "progTabPg": "Programming tab page",
  "progTabBack": "Back of programming tab page",
  "progPage1": "Programming page 1 en",
  "progPage2": "Programming page 2 en",
  "progPage3": "Programming page 3 en",
  "progPage4": "Programming page 4 en",
  "progPage5": "Programming page 5 en",
  "progPage6": "Programming page 6 en",
  "lastPage": "Last page",
  "end": "Cover of last page"
}

export const fr = {
  "title": "Les archives des Angrynieurs Mari",
  "toc": "Table des matières",
  "robotTitle": "Robot",
  "robotTabPg": "Onglet robot",
  "robotTabBack": "Verso de l'onglet robot",
  "robotImg1": "img src",
  "robotText1": "Texte pour img 1",
  "robotImg2": "img src",
  "robotText2": "Texte pour img 2",
  "robotImg3": "img src",
  "robotText3": "Texte pour img 3",
  "robotImg4": "img src",
  "robotText4": "Texte pour img 4",
  "robotImg5": "img src",
  "robotText5": "Texte pour img 5",
  "robotImg6": "img src",
  "robotText6": "Texte pour img 6",
  "robotImg7": "img src",
  "robotText7": "Texte pour img 7",
  "robotImg8": "img src",
  "robotText8": "Texte pour img 8",
  "robotImg9": "img src",
  "robotText9": "Texte pour img 9",
  "robotPage4": "Robot page 4 fr",
  "robotPage5": "Robot page 5 fr",
  "robotPage6": "Robot page 6 fr",
  "kioskTabPg": "Onglet kiosque",
  "kioskTabBack": "Verso de l'onglet kiosque",
  "kioskPage1": "Kiosque page 1 fr",
  "kioskPage2": "Kiosque page 2 fr",
  "kioskPage3": "Kiosque page 3 fr",
  "kioskPage4": "Kiosque page 4 fr",
  "kioskPage5": "Kiosque page 5 fr",
  "kioskPage6": "Kiosque page 6 fr",
  "websiteTabPg": "Onglet site web",
  "websiteTabBack": "Verso de l'onglet site web",
  "websitePage1": "Site web page 1 fr",
  "websitePage2": "Site web page 2 fr",
  "websitePage3": "Site web page 3 fr",
  "websitePage4": "Site web page 4 fr",
  "websitePage5": "Site web page 5 fr",
  "websitePage6": "Site web page 6 fr",
  "videoTabPg": "Onglet vidéo",
  "videoTabBack": "Verso de l'onglet vidéo",
  "videoPage1": "Vidéo page 1 fr",
  "videoPage2": "Vidéo page 2 fr",
  "videoPage3": "Vidéo page 3 fr",
  "videoPage4": "Vidéo page 4 fr",
  "videoPage5": "Vidéo page 5 fr",
  "videoPage6": "Vidéo page 6 fr",
  "progTabPg": "Onglet programmation",
  "progTabBack": "Verso de l'onglet programmation",
  "progPage1": "Programmation page 1 fr",
  "progPage2": "Programmation page 2 fr",
  "progPage3": "Programmation page 3 fr",
  "progPage4": "Programmation page 4 fr",
  "progPage5": "Programmation page 5 fr",
  "progPage6": "Programmation page 6 fr",
  "lastPage": "Dernier page",
  "end": "Couverture du dernier page"
}

const chapterPages = [2, 10, 18, 26, 34];

export const enTabs = {
  'Robot': chapterPages[0],
  'Kiosk': chapterPages[1],
  'Website': chapterPages[2],
  'Video': chapterPages[3],
  'Programming': chapterPages[4]
}

export const frTabs = {
  'Robot': chapterPages[0],
  'Kiosque': chapterPages[1],
  'Site web': chapterPages[2],
  'Vidéo': chapterPages[3],
  'Programmation': chapterPages[4]
}
