// content for archives pages
export const en = {
  "title": "The Mari Angryneer Archives",
  "toc": "Table of Contents",
  "intro1": "Once upon a time in the Bird Kingdom, a group of angryneers at Marianopolis banded together to form the Mari Angryneers…",
  "intro2": "They've come a long way and now, they're gearing up for the CRC's 2024 Kryptik Angryneering Competition. This priceless artifact contains the official 2023-24 Mari Angryneer Archives, so cherish this journal and protect it,",
  "robot": {
    "date1": "Nov 13, 2023: Kickoff!",
    "text1": "Angryneers from all over the Bird Kingdom gather at Curé-Antoine-Labelle high school, the site of the infamous angryneering competition held annually by the CRC, for the Kryptik 2024 kickoff!",
    "alt1": "8 members of the team standing in the École Curé-Antoine-Labelle auditorium.",
    "date2": "Nov 30, 2023",
    "text2": "The Mari Angryneers discuss the different intake mechanisms to pick up the game pieces from the ground, and split into small teams to each work on intake prototypes and on base.",
    "alt2": "A sketch of the robot design.",
    "date3": "Dec 7, 2023",
    "text3": "The robot angryneers settle on the dimensions of the base and wheelbase to optimise movement (especially while climbing the 12 degree slope toward the gutters) and start building the base. They continue prototyping throughout December.",
    "alt3": "3 members of the robot team building the frame for the robot.",
    "date4": "Jan 10, 2024",
    "text4": "The robot angryneers begin testing intake and double flywheel launching mechanisms with some promising results!",
    "alt4": "7 members of the robot team testing out the flywheel mechanism.",
    "date5": "Jan 11, 2024",
    "text5": "The robot angryneers complete the base frame and mecanum wheelbase alignment. They build a ramp and test the robot's ramp-climbing abilities. Success!",
    "alt5": "7 members of the robot team driving the robot onto a ramp.",
    "date6": "Jan 18, 2024",
    "text6": "The robot angryneers finalise the circuit board with some (not-so) innovative soldering techniques.",
    "alt6": "2 members of the robot team soldering motors.",
    "date7": "Feb 6, 2024",
    "text7": "A makeshift toboggan is assembled onto the robot for testing.",
    "alt7": "The robot with the makeshift toboggan made out of cardboard.",
    "date8": "Feb 20, 2024",
    "text8": "The robot angryneers build a shooting tower to test out the improved double flywheel system with new gearbox ratios. Success!",
    "alt8": "The tower with its vertical conveyor belt and double flywheel system.",
    "date9": "Mar 7, 2024",
    "text9": "After a long week of hard work, the robot angryneers have completed the toboggan, multiplier and intake systems to test a fully functional robot! They are very proud of how far the robot has come and will continue to make improvements.",
    "alt9": "The finalised version of the robot with all its functional systems."
  },
    "kiosk": {
    "date1": "Nov 30, 2023",
    "text1": "The kiosk angryneers begin finalizing colours and props to replicate the King Pig's castle for the annual Kryptik competition!",
    "alt1": "An early sketch of the Kiosk plan.",
    "date2": "Dec 28, 2023",
    "text2": "The walls of the castle replica are now set up and ready to be painted.",
    "alt2": "A team member holding a plank of wood in the kiosk.",
    "date3": "Jan 8, 2024",
    "text3": "The Mari Angryneers have their first in-person meeting of the new year. The kiosk angryneers apply primer to the walls to begin painting.",
    "alt3": "Two team members positioning the banner on the kiosk.",
    "date4": "Jan 9, 2024",
    "text4": "As some of the angryneers finish setting up the outer stone walls of the castle, others continue painting the interior walls green to resemble the original King Pig's castle.",
    "alt4": "Four team members preparing the paint and sponges for the kiosk.",
    "date5": "Jan 12, 2024",
    "text5": "Windows were installed to perfectly replicate the King Pig's castle and to enjoy the beautiful view of the birds' island",
    "alt5": "A team member sculpting the kiosk walls.",
    "date6": "Jan 18, 2024",
    "text6": "A custom green couch is created from green fabric and wooden frames to represent the King Pig.",
    "alt6": "Three team members painting the kiosk walls.",
    "date7": "Feb 8, 2024",
    "text7": "Velvet purple banners with a gold border are made and ready to be displayed on the castle's stone walls.",
    "alt7": "Three members of the team painting the kiosk in green.",
    "date8": "Feb 13, 2024",
    "text8": "Several Mari Angryneers work together to paint a stunning sky gradient on the walls outside of the castle.",
    "alt8": "Three team members placing the wooden frames for the kiosk windows.",
    "date9": "Feb 22, 2024",
    "text9": "The kiosk angryneers have found a better way to create a stone wall: they will carve foam boards and paint them grey.",
    "alt9": "A team member in the kiosk storage box.",
    "date10": "Mar 4, 2024",
    "text10": "Wooden beams are spray-painted gold for a more majestic look and installed around the interior of the castle. The King Pig's castle is coming together nicely!",
    "alt10": "A team member spray painting the kiosk's wooden planks.",
    "date11": "Mar 6, 2024",
    "text11": "The kiosk angryneers make plushies out of quilting fabric and Polyfill stuffing for three Mari Angryneers: Red, Chuck, and Black. Soon, they'll be able to invite the rest of the team to join them inside!",
    "alt11": "Two team members holding stuffing.",
  },
  "website": {
    "date1": "Nov 30, 2023",
    "text1": "The website angryneers begin discussing the content and structure of their 2024 Kryptik website, and decide to use Svelte and Bootstrap to develop the site this year!",
    "alt1": "Two team members working on the website.",
    "date2": "Dec 29, 2023",
    "text2": "The website angryneers meet online to start designing layouts and interactive components such as 3D models and scroll animations.",
    "alt2": "An early plan of the Kryptik web page.",
    "date3": "Jan 3, 2024",
    "text3": "Now that website design and ideas have been finalized, the website Mari Angryneers begin delegating tasks to work more efficiently.",
    "alt3": "Web page designs of the landing, Kryptik and home pages.",
    "date4": "Jan 8, 2024",
    "text4": "The website team moves swiftly in their work and finishes coding some reusable components and pages.",
    "alt4": "Two team members working on the website.",
    "date5": "Jan 10, 2024",
    "text5": "Ming (aka. Silver) works tirelessly to code an awesome 3D Kryptik simulation!",
    "alt5": "A team member working on the website.",
    "date6": "Feb 6, 2024",
    "text6": "Some pages of the website now have an initial version completed! The website angryneers continue to design and code the remaining pages, while debugging and improving the completed ones.",
    "alt6": "A team member coding the website.",
    "date7": "Mar 7, 2024",
    "text7": "The website angryneers have programmed all the pages, and only a few tasks are left: website content, improvements, and careful proofreading.",
    "alt7": "Two team members working on the website.",
    "date8": "Mar 8, 2024",
    "text8": "The website angryneers jot down their final updates on the team and present the website to finalize its features as the submission deadline approaches fast. Individual photos of the Mari Angryneers (not in bird form) are also taken and uploaded to the website!",
    "alt8": "Two team members testing out the camera.",
  },
  "video": {
    "date1": "Nov 30, 2023",
    "text1": "The video angryneers confirm that they will make a video tribute to the brave Angryneers who fought and won against the King Pig and his allies. The video will be played for all to see at the 2024 Kryptik Angryneering competition to make for an even more festive and exciting celebration!",
    "alt1": "Two team members discussing behind a laptop.",
    "date2": "Jan 8, 2024",
    "text2": "Some of the video props and costumes have now arrived. Here's a sneak peak of the action…",
    "alt2": "A team member inflating their pig suit.",
    "date3": "Jan 18, 2024",
    "text3": "Video angryneer Zi Heng (aka. Tony) gets some much needed rest after spending many late nights on the script.",
    "alt3": "A team member sleeping on the couch.",
    "date4": "Feb 6, 2024",
    "text4": "With a complete plan for the video, more props and costumes are ordered and on their way to the Mari Angryneers' base.",
    "alt4": "A team member in duck costume.",
    "date5": "Feb 15, 2024",
    "text5": "Video and other recording equipment has been delivered! The Mari Angryneers can't wait to create the video tribute and test their cameras to ensure they work as intended.",
    "alt5": "A team member taking pictures.",
    "date6": "Feb 29, 2024",
    "text6": "All the necessary props and tools are finally here. The video angryneers prepare for filming, and agree to create a tutorial on website design.",
    "alt6": "A team member in a green pig costume.",
    "date7": "Mar 4, 2024",
    "text7": "Today's a very exciting day: the Mari Angryneers begin filming the video!",
    "alt7": "Filming the scene with three pigs discussing.",
    "date8": "Mar 8, 2024",
    "text8": "Filming is complete after several days of hard work. Time to edit for the video angryneers!",
    "alt8": "Camera shot of the two pigs kneeling in front of the King Pig.",
  },
  "programming": {
    "date1": "Nov 19, 2023",
    "text1": "Thanks to Ming (aka. Silver) and Siva (aka. Chuck), the Programming Angryneers' initial solution to the first preliminary problem is complete.",
    "alt1": "List of steps to solve the first preliminary problem.",
    "date2": "Dec 3, 2023",
    "text2": "Aleksandr (aka. Hal) refactors our solution using Regex to cover more edge cases and adds more comments to improve readability. After some discussion, the Programming Angryneers submit their final solution for preliminary problem 1.",
    "alt2": "Team members discussing their progress on the preliminary problems on Discord.",
    "date3": "Jan 26, 2024",
    "text3": "Ming and Aleksandr collaborate to determine the most optimal solutions for each part of preliminary problem 2. Once they reach agreement, the Mari Angryneers make their final submission for this problem.",
    "alt3": "Comments of code discussing efficiency of program.",
    "date4": "Feb 5, 2024",
    "text4": "As soon as preliminary problem 3 is released, Ming and Aleksandr get to work.",
    "alt4": "File diff of two solutions for prelim 2 part 4.",
    "date5": "Feb 18, 2024",
    "text5": "After encountering some issues with lack of computing power and an overly long runtime for their solution to part 5, Ming and Aleksandr complete and submit the third preliminary problem.",
    "alt5": "One team member working on the preliminary problems.",
  },
  "lastPage": "Last page",
  "end": "The end"
}

export const fr = {
  "title": "Les archives des angrynieurs Mari",
  "toc": "Table des matières",
  "intro1": "Il était une fois dans le Royaume des oiseaux, un groupe d'angrynieurs à Marianopolis se regroupent pour former l'équipe des Angrynieurs Mari…",
  "intro2": "Ils ont parcouru un long chemin et maintenant ils se préparent pour la compétition d'angrynierie Kryptik 2024, organisée par la CRC. Cette œuvre inestimable contient les archives officielles de 2023-24 des Angrynieurs Mari, donc chérissez ce journal et protégez-le,",
  "robot": {
    "date1": "13 nov. 2023",
    "text1": "Les angrynieurs du Royaume des oiseaux se rassemblent à l'école secondaire Curé-Antoine-Labelle, le site de l'infâme compétition d'angrynierie organisée chaque année par le CRC, pour le coup d'envoi de Kryptik 2024 !",
    "alt1": "8 membres de l'équipe dans l'auditorium de l'école secondaire Curé-Antoine-Labelle.",
    "date2": "30 nov. 2023",
    "text2": "Les angrynieurs Mari discutent des différents mécanismes d'admission pour ramasser les pièces du jeu au sol et se divisent en petites équipes pour travailler sur les prototypes d'admission.",
    "alt2": "Une esquisse du design du robot.",
    "date3": "7 déc. 2023",
    "text3": "Les angrynieurs en robotique définissent les dimensions de la base et de l'empattement pour optimiser les déplacements (notamment pour gravir la pente de 12 degrés vers les gouttières). Ils commencent la construction de la base et continuent le prototypage tout au long du mois de décembre.",
    "alt3": "3 membres de l'équipe robotique en train de concevoir la base du robot.",
    "date4": "10 janv. 2024",
    "text4": "Les angrynieurs en robotique commencent à tester les mécanismes de lancement par admission et par double volant d'inertie, avec des résultats prometteurs!",
    "alt4": "7 membres de l'équipe robot en train de tester le mécanisme de lancement à double volant d'inertie.",
    "date5": "11 janv. 2024",
    "text5": "Les angrynieurs en robotique terminent l'alignement du cadre de base et des roues omnidirectionnelles mecanum. Ils construisent une rampe et testent les capacités d'escalade du robot. Succès!",
    "alt5": "7 membres de l'équipe robot en train de conduire le robot sur une rampe.",
    "date6": "18 janv. 2024",
    "text6": "Les angrynieurs en robotique finalisent le circuit électrique à l'aide de techniques de soudure (pas si) innovantes.",
    "alt6": "2 membres de l'équipe robotique en train de souder des moteurs.",
    "date7": "6 fév. 2024",
    "text7": "Un toboggan est assemblé sur le robot pour tester ses capacités de stockage des pièces de jeu.",
    "alt7": "Le robot muni d'un système toboggan en carton.",
    "date8": "20 fév. 2024",
    "text8": "Les angrynieurs Mari construisent une tour de tir pour tester le système amélioré de double volant d'inertie avec de nouveaux rapports de boîte de vitesses. Succès!",
    "alt8": "La tour avec son convoyeur vertical et le système à double volant d'inertie.",
    "date9": "7 mars",
    "text9": "Après une longue semaine de travail acharné, les robots angryneers ont terminé le toboggan, le multiplicateur et les systèmes d'admission pour tester un robot entièrement fonctionnel ! Ils sont très fiers du chemin parcouru par le robot et continueront à l'améliorer dans les semaines à venir.",
    "alt9": "Le robot finalisé avec tous ses systèmes fonctionnels."
  },
    "kiosk": {
    "date1": "30 nov. 2023",
    "text1": "Les angrynieurs Mari commencent à finaliser les couleurs et les accessoires afin de reproduire le château du Roi Cochon pour le concours annuel de Kryptik !",
    "alt1": "Un croquis du plan du kiosque.",
    "date2": "28 déc. 2023",
    "text2": "Les murs de la réplique du château sont maintenant installés et prêts à être peints.",
    "alt2": "Un membre de l'équipe qui tient une planche de bois dans le kiosque.",
    "date3": "8 janv. 2024",
    "text3": "Les angrynieurs Mari tiennent leur première réunion en personne de la nouvelle année. Les angrynieurs du kiosque appliquent une couche de fond sur les murs pour commencer à peindre.",
    "alt3": "Trois membres de l'équipe peignant les murs du kiosque.",
    "date4": "9 janv. 2024",
    "text4": "Tandis que certains angrynieurs finissent de monter les murs extérieurs en pierre du château, d'autres continuent de peindre les murs intérieurs en vert pour ressembler au château original du Roi Cochon.",
    "alt4": "Trois membres de l'équipe peignant le kiosque en vert.",
    "date5": "12 janv. 2024",
    "text5": "Des fenêtres ont été installées pour reproduire parfaitement le château du roi cochon et pour profiter de la vue magnifique sur l'île des oiseaux.",
    "alt5": "Trois membres de l'équipe plaçant les cadres en bois des fenêtres du kiosque.",
    "date6": "18 janv. 2024",
    "text6": "Un canapé vert personnalisé est créé à partir de tissu vert et de cadres en bois pour représenter le Roi Cochon.",
    "alt6": "Un membre de l'équipe de la boîte de stockage du kiosque.",
    "date7": "8 fév. 2024",
    "text7": "Des bannières de velours violet avec une bordure dorée sont fabriquées et prêtes à être affichées sur les murs de pierre du château.",
    "alt7": "Deux membres de l'équipe qui positionnent une bannière sur le kiosque.",
    "date8": "13 fév. 2024",
    "text8": "Plusieurs angrynieurs Mari travaillent ensemble pour peindre un magnifique dégradé de ciel sur les murs à l'extérieur du château.",
    "alt8": "Quatre membres de l'équipe qui préparent la peinture et les éponges pour le kiosque.",
    "date9": "22 fév. 2024",
    "text9": "Les angrynieurs du kiosque ont trouvé un meilleur moyen de créer un mur de pierre: ils vont sculpter des panneaux de mousse et les peindre en gris.",
    "alt9": "Un membre de l'équipe sculptant le mur du kiosque.",
    "date10": "4 mars 2024",
    "text10": "Des poutres en bois sont peintes en or pour un aspect plus majestueux et sont installées à l'intérieur du château. Le château du roi cochon prend forme !",
    "alt10": "Un membre de l'équipe qui peint à l'aérosol les planches de bois du kiosque.",
    "date11": "6 mars 2024",
    "text11": "Les angrynieurs du kiosque fabriquent des peluches avec du tissu et du rembourrage Polyfill pour trois angrynieurs Mari: Red, Chuck et Black. Bientôt, ils pourront inviter le reste de l'équipe à les rejoindre à l'intérieur !",
    "alt11": "Deux membres de l'équipe qui tiennent du rembourrage.",
  },
  "website": {
    "date1": "30 nov. 2023",
    "text1": "Les angrynieurs du site web commencent à discuter du contenu et de la structure de leur site web Kryptik 2024, et décident d'utiliser Svelte et Bootstrap pour développer le site cette année !",
    "alt1": "Deux membres de l'équipe travaillant sur le site web.",
    "date2": "29 déc. 2023",
    "text2": "Les membres du groupe se réunissent en ligne pour commencer à concevoir des mises en page et des éléments interactifs tels que des modèles 3D et des animations de défilement.",
    "alt2": "Un plan de la page Kryptik du site web.",
    "date3": "3 janv. 2024",
    "text3": "Maintenant que la conception du site et les idées ont été finalisées, les angrynieurs du site web commencent à déléguer des tâches pour travailler plus efficacement.",
    "alt3": "Plan des pages web pour les pages de destination, d'accueil et de Kryptik.",
    "date4": "8 janv. 2024",
    "text4": "L'équipe du site web avance rapidement dans son travail et termine le codage de certains composants et pages réutilisables.",
    "alt4": "Deux membres de l'équipe travaillant sur le site web.",
    "date5": "10 janv. 2024",
    "text5": "Ming (aka. Silver) travaille sans relâche pour coder une impressionnante simulation 3D de Kryptik !",
    "alt5": "Un membre de l'équipe travaillant sur le site web.",
    "date6": "6 fév. 2024",
    "text6": "Certaines pages du site web ont maintenant une version initiale complétée ! Les angrynieurs du site continuent de concevoir et de coder les pages restantes, tout en déboguant et en améliorant celles qui sont terminées.",
    "alt6": "Un membre de l'équipe programmant le site web.",
    "date7": "7 mars 2024",
    "text7": "Les angrynieurs du site web ont programmé toutes les pages, et il ne reste plus que quelques tâches: le contenu du site, les améliorations, et une relecture minutieuse.",
    "alt7": "Deux membres de l'équipe travaillant sur le site web.",
    "date8": "8 mars 2024",
    "text8": "Les angrynieurs du site web notent leurs dernières mises à jour sur l'équipe et présentent le site web pour en finaliser les fonctionnalités alors que la date limite de soumission approche à grands pas. Des photos individuelles des angrynieurs Mari (pas sous forme d'oiseau) sont également prises et téléchargées sur le site web !",
    "alt8": "Deux membres de l'équipe testant la caméra.",
  },
  "video": {
    "date1": "30 nov. 2023",
    "text1": "Les angrynieurs vidéo confirment qu'ils vont réaliser une vidéo en hommage aux braves angrynieurs qui ont triomphé contre le Roi Cochon et ses alliés. La vidéo sera diffusée lors de la compétition d'angrynierie de Kryptik 2024, pour une célébration encore plus festive et excitante !",
    "alt1": "Deux membres de l'équipe discutant derrière un ordinateur portable.",
    "date2": "8 janv. 2024",
    "text2": "Certains accessoires et costumes de la vidéo sont arrivés. Voici un aperçu de l'action...",
    "alt2": "Un membre de l'équipe gonflant son costume de cochon.",
    "date3": "18 janv. 2024",
    "text3": "Zi Heng (alias Tony), angrynieur vidéo, prend un peu de repos bien mérité après avoir passé de nombreuses nuits sur le scénario.",
    "alt3": "Un membre de l'équipe qui dort sur le sofa.	",
    "date4": "6 fév. 2024",
    "text4": "Avec un plan complet pour la vidéo, plus d'accessoires et de costumes sont commandés et en route vers la base des angrynieurs de Mari.",
    "alt4": "Un membre de l'équipe en costume de canard.",
    "date5": "15 fév. 2024",
    "text5": "La vidéo et le matériel d'enregistrement ont été livrés ! Les angrynieurs Mari sont impatients de créer l'hommage vidéo et de tester leurs caméras pour s'assurer qu'elles fonctionnent comme prévu.",
    "alt5": "Un membre de l'équipe qui prend des photos.",
    "date6": "29 fév. 2024",
    "text6": "Tous les accessoires et outils nécessaires sont enfin arrivés. Les angrynieurs vidéo se préparent au tournage, et se mettent d'accord pour créer un tutoriel sur la conception web.",
    "alt6": "Un membre de l'équipe en costume de cochon vert.",
    "date7": "4 mars 2024",
    "text7": "Aujourd'hui est un jour très excitant: les angrynieurs Mari commencent à filmer la vidéo !",
    "alt7": "Enregistrement de la scène avec trois cochons.",
    "date8": "8 mars 2024",
    "text8": "Le tournage est terminé après plusieurs jours de travail acharné. Il est temps de faire le montage pour la vidéo des angrynieurs!",
    "alt8": "Capture de la caméra filmant les deux cochons qui s'agenouillent devant le roi cochon.",
  },
  "programming": {
    "date1": "19 nov. 2023",
    "text1": "Grâce à Ming (aka. Hal) et Siva (aka. Chuck), les Angrynieurs logiciel développent leur solution initiale au premier problème préliminaire.",
    "alt1": "Deux membres de l'équipe travaillant sur le premier problème préliminaire.",
    "date2": "3 déc. 2023",
    "text2": "Aleksandr (aka. Hal) retravaille le code en utilisant des expressions régulières (Regex) afin de couvrir plus de cas limites, et il ajoute des commentaires pour améliorer la lisibilité des programmes. Après une brève discussion, les Angrynieurs logiciel remettent leur solution finale pour le premier problème préliminaire.",
    "alt2": "Liste d'étapes de la solution générale pour résoudre le premier problème préliminaire.",
    "date3": "26 janv. 2024",
    "text3": "Ming et Aleksandr collaborent pour déterminer les solutions les plus optimales pour chaque partie du deuxième problème préliminaire. Une fois les décisions prises, les Angrynieurs Mari préparent leur soumission finale pour ce problème.",
    "alt3": "Différenciation de fichier pour deux solutions à la partie 4 du deuxième problème préliminaire.",
    "date4": "5 fév. 2024",
    "text4": "Dès la publication du troisième problème préliminaire, Ming et Aleksandr se mettent au travail.",
    "alt4": "Membres de l'équipe ayant une discussion sur le progrès des problèmes préliminaires de programmation sur Discord.",
    "date5": "18 fév. 2024",
    "text5": "Ming et Aleksandr se heurtent à des difficultés avec la cinquième partie du problème: leur solution initiale exige trop de puissance informatique et prend trop de temps pour s'exécuter. Pourtant, ils surmontent ces obstacles réussissent à remettre le troisième problème préliminaire.",
    "alt5": "Un membre de l'équipe travaillant sur les problèmes préliminaires.",
  },
  "lastPage": "Last page",
  "end": "La fin"
}

export const imgs = {
  "robot": {
    "img1": "robot/nov-13.jpg",
    "img2": "robot/nov-30.jpg",
    "img3": "robot/dec-7.jpg",
    "img4": "robot/jan-10.jpg",
    "img5": "robot/jan-11.jpg",
    "img6": "robot/jan-18.jpg",
    "img7": "robot/feb-6.jpg",
    "img8": "robot/feb-20.jpg",
    "img9": "robot/mar-7.jpg"
  },
  "kiosk": {
    "img1": "kiosk/nov-30.jpg",
    "img2": "kiosk/dec-28.jpg",
    "img3": "kiosk/jan-8.jpg",
    "img4": "kiosk/jan-9.jpg",
    "img5": "kiosk/jan-12.jpg",
    "img6": "kiosk/jan-18.jpg",
    "img7": "kiosk/feb-8.jpg",
    "img8": "kiosk/feb-13.jpg",
    "img9": "kiosk/feb-22.jpg",
    "img10": "kiosk/mar-4.jpg",
    "img11": "kiosk/mar-6.jpg"
  },
  "website": {
    "img1": "website/nov-30.jpg",
    "img2-en": "website/dec-29-en.jpg",
    "img2-fr": "website/dec-29-fr.jpg",
    "img3": "website/jan-3.jpg",
    "img4": "website/jan-8.jpg",
    "img5": "website/jan-10.jpg",
    "img6": "website/feb-6.jpg",
    "img7": "website/mar-7.jpg",
    "img8": "website/mar-8.jpg"
  },
  "video": {
    "img1": "video/nov-30.jpg",
    "img2": "video/jan-8.jpg",
    "img3": "video/jan-18.jpg",
    "img4": "video/feb-6.jpg",
    "img5": "video/feb-15.jpg",
    "img6": "video/feb-29.jpg",
    "img7": "video/mar-4.jpg",
    "img8": "video/mar-8.jpg",
  },
  "programming": {
    "img1": "programming/nov-19.jpg",
    "img2": "programming/dec-3.jpg",
    "img3": "programming/jan-26.jpg",
    "img4": "programming/feb-5.jpg",
    "img5": "programming/feb-18.jpg"
  }
}

const chapterPages = [3, 8, 14, 26, 34];
const mobileChapterPages = [3, 15, 23, 29, 38];

export const enTabs = {
  'Robot': [chapterPages[0], chapterPages[1] - 1],
  'Kiosk': [chapterPages[1], chapterPages[2] - 1],
  'Website': [chapterPages[2], chapterPages[3] - 1],
  'Video': [chapterPages[3], chapterPages[4] - 1],
  'Programming': [chapterPages[4], 50]
}

export const frTabs = {
  'Robot': [chapterPages[0], chapterPages[1] - 1],
  'Kiosque': [chapterPages[1], chapterPages[2] - 1],
  'Site web': [chapterPages[2], chapterPages[3] - 1],
  'Vidéo': [chapterPages[3], chapterPages[4] - 1],
  'Programmation': [chapterPages[4], 50]
}

export const enSmTabs = {
  'Robot': [mobileChapterPages[0], mobileChapterPages[1] - 1],
  'Kiosk': [mobileChapterPages[1], mobileChapterPages[2] - 1],
  'Web': [mobileChapterPages[2], mobileChapterPages[3] - 1],
  'Vid': [mobileChapterPages[3], mobileChapterPages[4] - 1],
  'Prog': [mobileChapterPages[4], 50]
}

export const frSmTabs = {
  'Robot': [mobileChapterPages[0], mobileChapterPages[1] - 1],
  'Kiosque': [mobileChapterPages[1], mobileChapterPages[2] - 1],
  'Web': [mobileChapterPages[2], mobileChapterPages[3] - 1],
  'Vid': [mobileChapterPages[3], mobileChapterPages[4] - 1],
  'Prog': [mobileChapterPages[4], 50]
}
